const NOTIFICATION_CHANGE_USER_DATA = 'changeUserData';
const NOTIFICATION_SHOW_LOGIN = 'showLoginView';
const NOTIFICATION_SHOW_COMMENT = 'showCommentView';
const NOTIFICATION_SHOW_GETUSERINFO = 'showGetUserInfoView';
const NOTIFICATION_SHOW_GETPHONE = 'showGetPhoneView';


module.exports={
  NOTIFICATION_CHANGE_USER_DATA,
  NOTIFICATION_SHOW_LOGIN,
  NOTIFICATION_SHOW_COMMENT,
  NOTIFICATION_SHOW_GETUSERINFO,
  NOTIFICATION_SHOW_GETPHONE
}