const NOTIFICATION_CHANGE_USER_DATA = 'changeUserData';
const NOTIFICATION_SHOW_LOGIN = 'showLoginView';
const NOTIFICATION_SHOW_COMMENT = 'showCommentView';


module.exports={
  NOTIFICATION_CHANGE_USER_DATA,
  NOTIFICATION_SHOW_LOGIN,
  NOTIFICATION_SHOW_COMMENT
}